#!/usr/bin/env python3
"""Sync the library into the Home Assistant component as a vendored copy.

The component must be installable by copying one folder into
/config/custom_components with no PyPI publish step, so it carries its own
copy of ``src/myusage_archive``. This script is the only way that copy may
change; CI runs ``--check`` so the two can never drift.

    python scripts/vendor.py          # sync src -> vendor
    python scripts/vendor.py --check  # exit 1 if out of sync
"""

from __future__ import annotations

import filecmp
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "myusage_archive"
VENDOR = ROOT / "custom_components" / "myusage_archive" / "vendor"
DST = VENDOR / "myusage_archive"

# CLI-only modules are not needed inside Home Assistant.
EXCLUDE = {"__main__.py", "cli.py", "probe.py", "anonymize.py"}
MARKER = (
    '"""Vendored copy of the myusage-archive library.\n\n'
    "Generated by scripts/vendor.py from src/myusage_archive - do not edit here.\n"
    '"""\n'
)


def wanted() -> list[Path]:
    return sorted(
        p for p in SRC.iterdir()
        if p.is_file() and p.name not in EXCLUDE and (p.suffix == ".py" or p.name == "py.typed")
    )


def sync() -> None:
    DST.mkdir(parents=True, exist_ok=True)
    (VENDOR / "__init__.py").write_text(MARKER, encoding="utf-8")
    names = set()
    for src in wanted():
        shutil.copyfile(src, DST / src.name)
        names.add(src.name)
    for stale in DST.iterdir():
        if stale.is_file() and stale.name not in names:
            stale.unlink()
    print(f"vendored {len(names)} files into {DST.relative_to(ROOT)}")


def check() -> bool:
    ok = True
    present = {p.name for p in DST.iterdir() if p.is_file()} if DST.exists() else set()
    for src in wanted():
        dst = DST / src.name
        if not dst.exists() or not filecmp.cmp(src, dst, shallow=False):
            print(f"out of sync: {src.name}")
            ok = False
        present.discard(src.name)
    for extra in sorted(present):
        print(f"stale vendored file: {extra}")
        ok = False
    if not (VENDOR / "__init__.py").exists():
        print("missing vendor/__init__.py")
        ok = False
    print("vendored copy is in sync" if ok else "run: python scripts/vendor.py")
    return ok


if __name__ == "__main__":
    if "--check" in sys.argv:
        raise SystemExit(0 if check() else 1)
    sync()
